spring.application.name=ZymProductsOrderingProject

spring.datasource.url=jdbc:postgresql://localhost:5432/ecart
spring.datasource.username=postgres
spring.datasource.password=Aripaka@1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081


razorpay.key=rzp_live_ScXL69ffuvJAFt
razorpay.secret=sKKlux1Lm8cU4xQp064NHo9n

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true