spring.application.name=ZymProductsOrderingProject
spring.datasource.url=jdbc:postgresql://<RDS-ENDPOINT>:5432/<DB-NAME>
spring.datasource.username=<USERNAME>
spring.datasource.password=<PASSWORD>
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8081
spring.web.resources.add-mappings=false
cors.allowed-origins=https://<CLOUDFRONT-DOMAIN>,http://localhost:5173
razorpay.key=rzp_live_SfPj8SfZggPOsI
razorpay.secret=XxzCTOWNX3sBMCvaR5gKOneV
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=udaykumararipaka@gmail.com
spring.mail.password=oicp ivnd kpuv ezzb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
file.upload-dir=uploads
jwt.secret=Qk9hZ3pXc2p5RkZqU2hYd1h5ZkRrVnNqR3p0cE5uY1dQd1pYd3h0U2p5RkZqU2hYd1h5ZkRrVnM=
jwt.expiration-ms=86400000
fast2sms.api.key=kJZznWcqx9Ym6w5PKgOesAyVlaMDGpTt0Cb1h28RiIQfUSN3F4CUEPgAsn5uwQLzGIlXKZY263VhD7rF

